### ISSUE TITLE
Migration to Python3

### ISSUE THREAD

**Issue by hosiet** [debiancn/galternatives#1]
We need to migrate all python scripts to python3 syntax.

**Comment by yangfl** [comment]
The code is quite simple and straightforward. With some care we can easily make it Python 2/3 compatible in the future.
The key point is to move away from the outdated pygtk module.

**Comment by hosiet** [comment]
Work in progress. Check out `glade3` branch.

I believe migration to python3 also means moving away from old `pygtk` module. Those tasks are combined.
