### ISSUE TITLE
Description on alternative name

### ISSUE THREAD

**Issue by yangfl** [debiancn/galternatives#10]
Currently the latest stable version provides a strange way to supply a short description on the alternative name by using an almost-vaild .desktop file. However after some searches I can't find any more of such files nor descriptions. So I'd suggest:
* provide more descriptions using the old way
* provide more descriptions directly using gettext
* remove the description feature at all (since it's quite a huge task)
Which one do you perfer?

**Comment by hosiet** [comment]
* Description function is provided by `galternatives` only. It is not part of Debian's `alternatives` system.
* Old way (`.desktop` files) does not conflict with `gettext`. With proper tools, we can still extract and update (translatable) strings inside `.desktop` files.

A combination of two should be ideal, but it needs investigation.

**Comment by yangfl** [comment]
Shouldn't lots of trivial files be a huge burden?
