### ISSUE TITLE
Review i18n/l10n workflow

### ISSUE THREAD

**Issue by hosiet** [debiancn/galternatives#11]
We need to sort out the i18n/l10n workflow.

* `.glade` files contains some strings that need translation. (perhaps we need `xgettext`?)
* `.py` module needs translation.

We should write some scripts / Makefile targets / update current scripts to make sure things go on smoothly.

**Comment by yangfl** [comment]
Ready to be merged.

**Comment by hosiet** [comment]
Looks great✓

**Comment by hosiet** [comment]
Yet current tool fails to extract translatable strings in `galternatives.glade`.

**Comment by yangfl** [comment]
I'm not familiar with glade. Is `galternatives.h` autogenerated?
