### ISSUE TITLE
zh_CN.po and zh_TW.po have problem with {2} {4}

### ISSUE THREAD

**Issue by scootergrisen** [debiancn/galternatives#18]
zh_CN.po and zh_TW.po have a problem with these translations where it says 3 and 2 in the source but 2 and 4 in the translations (4 does not exists in the source string).

Maybe someone who knows chinese can fix it.

zh_CN.po:

    #: ../../galternatives/description.py:140
    #, python-brace-format
    msgid "Install option `{3}' for group `{2}'"
    msgstr "为组`{2}'安装选项 {4}"

zh_TW.po:

    #: ../../galternatives/description.py:140
    #, python-brace-format
    msgid "Install option `{3}' for group `{2}'"
    msgstr "為組`{2}'安裝選項 {4}"

**Comment by yangfl** [comment]
Fix in salsa, thanks!
