### ISSUE TITLE
Splitting frontend/backend code in python scripts

### ISSUE THREAD

**Issue by hosiet** [debiancn/galternatives#2]
We wish to split current code into two parts:

* A `python3-galternatives` library, which only deal with manipulation of Debian `alternatives` system;
* Some frontend code as an application.

**Comment by yangfl** [comment]
After some investigation I've found the backend is quite simple and contains strange and frustrated features. Wrapping a library may not be of too much help.

**Comment by yangfl** [comment]
Ok I've written a simple library to manipulate this. You can take a look at my repo.
