### ISSUE TITLE
Research on permissions and integration with polkit

### ISSUE THREAD

**Issue by hosiet** [debiancn/galternatives#4]
Currently `galternatives` does not need root password to gain root permission. We need to learn how it works and see what we can do.

**Comment by yangfl** [comment]
Isn't current version using gksu to gain root?

**Comment by hosiet** [comment]
Not really.

![_053](https://cloud.githubusercontent.com/assets/8443926/26731208/dd5d2f7a-47e5-11e7-8787-4975bc280793.png)

I'm not sure where that came from. Perhaps it is a message from `gksu`?

* * *

Yes that info was from `gksu`. We should try to migrate and use `polkit` as the first option, gksu as fallback.
